name: CI build

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

  build:
    name: Build Jar
    needs: check_wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Jar
        env:
          ProductBuildType: "Preview"
          # زيادة ذاكرة الجافا للنظام ككل
          _JAVA_OPTIONS: "-Xmx4g"
        working-directory: master
        # إضافة إعدادات الذاكرة لـ Gradle ولـ Kotlin Daemon مباشرة
        run: ./gradlew :server:shadowJar --stacktrace -Dorg.gradle.jvmargs="-Xmx4g" -Dkotlin.daemon.jvmargs="-Xmx4g"

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: master/server/build/*.jar

  jlink:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false 
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x64
          - os: windows-latest
            name: windows-x64
          - os: macos-latest
            name: macOS-arm64
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Package JDK
        run: jlink --add-modules java.base,java.compiler,java.desktop,java.logging,java.management,java.naming,java.security.jgss,java.sql,java.xml,jdk.attach,jdk.unsupported --output suwa --strip-debug --no-man-pages --no-header-files --compress=2
      - name: Upload JRE package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-jre
          path: suwa

  check_regex_success:
    name: Final Check
    needs: [build] 
    runs-on: ubuntu-latest
    steps:
      - name: Status
        run: echo "إذا وصلت هنا بنجاح، فهذا يعني أن تعديل الـ Regex والـ localhost في الكود سليم تماماً."
